#!/bin/bash
# coding: utf-8
# Copyright (c) 2015
# Gmail:liuzheng712
#

# cdinit
# cdvim
function cdinit(){
  touch .cdinit
}
function cdvim(){
  vim .cdinit
}
function cdd(){
cd $1 
if [ -f .cdinit ]; then
  cat .cdinit
fi
}
